<?php

namespace App\Console\Commands;

use App\Mail\BonSigned;
use App\Mail\CertificateIssued;
use App\Mail\InvoiceSent;
use App\Mail\OrderCreated;
use App\Models\Bon;
use App\Models\Certificate;
use App\Models\Customer;
use App\Models\Invoice;
use App\Models\Order;
use App\Models\Seal;
use App\Models\User;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Mail;

/**
 * End-to-end smoke test of the order pipeline.
 *
 * Creates a realistic test order for the given e-mail and (optionally) walks it
 * all the way through pickup -> destruction -> invoice, sending every customer
 * e-mail with its localized PDF attachment. Records are tagged [TEST] and use a
 * dedicated test customer so they are easy to spot and remove afterwards.
 *
 *   php artisan desnipperaar:test-order
 *   php artisan desnipperaar:test-order info@itomoti.com --full --locale=fr
 */
class SendTestOrder extends Command
{
    protected $signature = 'desnipperaar:test-order
        {email=info@itomoti.com : Recipient e-mail address}
        {--locale=nl : Customer locale (nl, en, fr, es)}
        {--full : Run the whole lifecycle: order, signed bon, certificate and invoice}
        {--boxes=4 : Number of boxes}
        {--containers=1 : Number of 240 L roll containers}';

    protected $description = 'Create a test order (optionally the full pipeline) and send the customer e-mails to a chosen address.';

    public function handle(): int
    {
        $email  = (string) $this->argument('email');
        $locale = strtolower((string) $this->option('locale'));
        $full   = (bool) $this->option('full');
        $boxes  = (int) $this->option('boxes');
        $cntrs  = (int) $this->option('containers');

        if (! in_array($locale, ['nl', 'en', 'fr', 'es'], true)) {
            $this->error("Invalid locale '{$locale}'. Use one of: nl, en, fr, es.");
            return self::FAILURE;
        }

        $this->info("Creating test order for {$email} (locale={$locale}, full=" . ($full ? 'yes' : 'no') . ')');

        $sender = User::orderBy('id')->first();
        $media  = ['hdd' => 1, 'usb' => 2];

        // 1034DN sits inside the Amsterdam pilot range, so the pilot discount is exercised too.
        $postcode = '1034DN';
        $numeric  = (int) substr($postcode, 0, 4);
        $pilot    = $numeric >= config('desnipperaar.pilot.postcode_start')
                 && $numeric <= config('desnipperaar.pilot.postcode_end');

        // Fake, clearly-marked numbers that do NOT match the real "PREFIX-YEAR-%"
        // pattern, so production order/bon/certificate/invoice sequences are never
        // advanced by a test run.
        $token = now()->format('ymd-His') . '-' . strtoupper(bin2hex(random_bytes(2)));

        $customer = Customer::updateOrCreate(
            ['email' => $email],
            [
                'name'      => 'Test Bestelling',
                'company'   => 'Itomoti (TEST)',
                'phone'     => '+31 6 1022 9965',
                'address'   => 'Teststraat 1',
                'postcode'  => $postcode,
                'city'      => 'Amsterdam',
                'reference' => 'TEST',
                'locale'    => $locale,
                'notes'     => '[TEST] Automated test customer — desnipperaar:test-order',
            ],
        );

        $order = Order::create([
            'order_number'       => "TEST-O-{$token}",
            'type'               => Order::TYPE_DIRECT,
            'customer_id'        => $customer->id,
            'created_by_user_id' => $sender?->id,
            'customer_name'      => $customer->name,
            'customer_email'     => $email,
            'customer_phone'     => $customer->phone,
            'customer_address'   => $customer->address,
            'customer_postcode'  => $customer->postcode,
            'customer_city'      => $customer->city,
            'customer_reference' => $customer->reference,
            'locale'             => $locale,
            'delivery_mode'      => Bon::MODE_OPHAAL,
            'box_count'          => $boxes,
            'container_count'    => $cntrs,
            'media_items'        => $media,
            'pickup_date'        => now()->addDay()->toDateString(),
            'pickup_window'      => 'ochtend',
            'notes'              => '[TEST ORDER] Generated by desnipperaar:test-order',
            'state'              => Order::STATE_NIEUW,
            'pilot'              => $pilot,
            'first_box_free'     => false,
        ]);

        $rows = [];
        $rows[] = ['Order', $order->order_number, $this->mail($email, fn () => new OrderCreated($order, $sender))];

        if ($full) {
            $bon = Bon::create([
                'bon_number'           => "TEST-P-{$token}",
                'order_id'             => $order->id,
                'driver_name_snapshot' => 'Test Chauffeur',
                'driver_license_last4' => '1234',
                'mode'                 => Bon::MODE_OPHAAL,
                'actual_boxes'         => $boxes,
                'actual_containers'    => $cntrs,
                'actual_media'         => $media,
                'picked_up_at'         => now(),
                'weight_kg'            => 47.5,
                'notes'                => '[TEST] Automated pickup',
            ]);

            foreach ([["TEST-SEAL-{$token}-1", 'rolcontainer_240'], ["TEST-SEAL-{$token}-2", 'doos']] as [$sn, $type]) {
                Seal::create([
                    'bon_id'         => $bon->id,
                    'seal_number'    => $sn,
                    'container_type' => $type,
                ]);
            }
            $bon->load('seals');
            $order->update(['state' => Order::STATE_OPGEHAALD]);
            $rows[] = ['Bon (pickup)', $bon->bon_number, $this->mail($email, fn () => new BonSigned($bon, $sender))];

            $certificate = Certificate::create([
                'certificate_number'  => "TEST-C-{$token}",
                'order_id'            => $order->id,
                'destroyed_at'        => now(),
                'weight_kg_final'     => 47.5,
                'destruction_method'  => 'DIN 66399 P-5',
                'operator_name'       => 'Test Operator',
            ]);
            $order->update(['state' => Order::STATE_VERNIETIGD]);
            $rows[] = ['Certificate', $certificate->certificate_number, $this->mail($email, fn () => new CertificateIssued($certificate, $sender))];

            // fromBon() assigns a real F-number internally; overwrite it with a fake
            // one so the real invoice sequence is not consumed. Done before the e-mail
            // so the PDF shows the fake number.
            $invoice = Invoice::fromBon($bon);
            $invoice->update(['invoice_number' => "TEST-F-{$token}"]);
            $order->update(['state' => Order::STATE_AFGESLOTEN]);
            $rows[] = ['Invoice', $invoice->invoice_number, $this->mail($email, fn () => new InvoiceSent($invoice, $sender))];
        }

        $this->newLine();
        $this->table(['Document', 'Number', 'E-mail'], $rows);
        $this->newLine();
        $this->info('Done. Records are tagged [TEST]; remove with:');
        $this->line("  php artisan tinker --execute='\\App\\Models\\Order::where(\"customer_email\",\"{$email}\")->each(fn(\$o)=>\$o->delete());'");

        return self::SUCCESS;
    }

    /** Send a mailable and return a short status string for the summary table. */
    private function mail(string $email, \Closure $make): string
    {
        try {
            Mail::to($email)->send($make());
            return '✓ sent';
        } catch (\Throwable $e) {
            report($e);
            return '✗ ' . $e->getMessage();
        }
    }
}
